backend:
  name: git-gateway
  branch: frankie/master_gatsby-structure

media_folder: static/img
public_folder: /img

collections:
  - label: 'imageGallery'
    name: 'imageGallery'
    folder: /static/img
    create: true
    media_folder: '/static/img/'
    description: 'PicList'
    # widget: 'image'
    # folder: '/data/photos.json'
    # default: '/static/img'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
